version: '3'
services:
  postgres:
    build:
      context: ./postgres   
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./postgres/.env  

  clickhouse:
    build:
      context: ./clickhouse
    ports:
      - "8123:8123"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    env_file:
      - ./clickhouse/.env  

  app:
    build:
      context: ./app
    ports:
      - "3000:3000"
    env_file:
      - ./app/.env  
    depends_on:
      - postgres
      - clickhouse

volumes:
  postgres-data:
  clickhouse-data:
