version: '3'
services:
  postgres:
    build:
      context: ./postgres   
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./postgres/.env  

  clickhouse:
    build:
      context: ./clickhouse
    ports:
      - "8123:8123"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    env_file:
      - ./clickhouse/.env  

  api:
    build:
      context: ./API
    ports:
      - "3000:3000"
    env_file:
      - ./API/.env  
    depends_on:
      - postgres
      - clickhouse

  click_service:
    build:
      context: ./clickService
    ports:
      - "3002:3002"
    env_file:
      - ./clickService/.env  
    depends_on:
      - postgres 

  auth_service: 
    build:
      context: ./authService
    ports:
      - "3003:3003" 
    env_file:
      - ./authService/.env
    depends_on:
      - postgres    

volumes:
  postgres-data:
  clickhouse-data:
