export const dataFromDatabase = [
  {
    'id': 1,
    'name': 'Оффер1',
    'categories': '-',
    'client': 'Рекламодатель1',
    'webmaster': '-',
    'status': 'Активен',
    'privateLevel': 'Публичный',
    'weekCr': 4.4,
    'cap': '-',
    'dailyLimit': '-',
    'totalLimit': '-',
    'today': 2,
    'payment': 350,
    'income': '-',
    'notes': '-'
  },
  {
    'id': 2,
    'name': 'Оффер2',
    'categories': '-',
    'client': 'Рекламодатель2',
    'webmaster': '-',
    'status': 'Активен',
    'privateLevel': 'Публичный',
    'weekCr': 3.2,
    'cap': '-',
    'dailyLimit': '-',
    'totalLimit': '-',
    'today': 3,
    'payment': 420,
    'income': '-',
    'notes': '-'
  },
  {
    'id': 3,
    'name': 'Оффер3',
    'categories': '-',
    'client': 'Рекламодатель3',
    'webmaster': '-',
    'status': 'Активен',
    'privateLevel': 'Публичный',
    'weekCr': 5.1,
    'cap': '-',
    'dailyLimit': '-',
    'totalLimit': '-',
    'today': 1,
    'payment': 300,
    'income': '-',
    'notes': '-'
  },
  {
    'id': 4,
    'name': 'Оффер4',
    'categories': '-',
    'client': 'Рекламодатель4',
    'webmaster': '-',
    'status': 'Активен',
    'privateLevel': 'Публичный',
    'weekCr': 4.8,
    'cap': '-',
    'dailyLimit': '-',
    'totalLimit': '-',
    'today': 0,
    'payment': 250,
    'income': '-',
    'notes': '-'
  },
  {
    'id': 5,
    'name': 'Оффер5',
    'categories': '-',
    'client': 'Рекламодатель5',
    'webmaster': '-',
    'status': 'Активен',
    'privateLevel': 'Публичный',
    'weekCr': 4.0,
    'cap': '-',
    'dailyLimit': '-',
    'totalLimit': '-',
    'today': 4,
    'payment': 380,
    'income': '-',
    'notes': '-'
  },
  {
    'id': 6,
    'name': 'Оффер6',
    'categories': '-',
    'client': 'Рекламодатель6',
    'webmaster': '-',
    'status': 'Активен',
    'privateLevel': 'Публичный',
    'weekCr': 3.5,
    'cap': '-',
    'dailyLimit': '-',
    'totalLimit': '-',
    'today': 5,
    'payment': 450,
    'income': '-',
    'notes': '-'
  },
  {
    'id': 7,
    'name': 'Оффер7',
    'categories': '-',
    'client': 'Рекламодатель7',
    'webmaster': '-',
    'status': 'Активен',
    'privateLevel': 'Публичный',
    'weekCr': 4.2,
    'cap': '-',
    'dailyLimit': '-',
    'totalLimit': '-',
    'today': 2,
    'payment': 370,
    'income': '-',
    'notes': '-'
  },
  {
    'id': 8,
    'name': 'Оффер8',
    'categories': '-',
    'client': 'Рекламодатель8',
    'webmaster': '-',
    'status': 'Активен',
    'privateLevel': 'Публичный',
    'weekCr': 4.6,
    'cap': '-',
    'dailyLimit': '-',
    'totalLimit': '-',
    'today': 3,
    'payment': 400,
    'income': '-',
    'notes': '-'
  },
  {
    'id': 9,
    'name': 'Оффер9',
    'categories': '-',
    'client': 'Рекламодатель9',
    'webmaster': '-',
    'status': 'Активен',
    'privateLevel': 'Публичный',
    'weekCr': 3.8,
    'cap': '-',
    'dailyLimit': '-',
    'totalLimit': '-',
    'today': 1,
    'payment': 280,
    'income': '-',
    'notes': '-'
  },
  {
    'id': 10,
    'name': 'Оффер10',
    'categories': '-',
    'client': 'Рекламодатель10',
    'webmaster': '-',
    'status': 'Активен',
    'privateLevel': 'Публичный',
    'weekCr': 4.1,
    'cap': '-',
    'dailyLimit': '-',
    'totalLimit': '-',
    'today': 6,
    'payment': 500,
    'income': '-',
    'notes': '-'
  }
]

