// mockData.js
export const columns = [
    'ID',
    'Название',
    'URL',
    'Цена клика',
    'Страна',
    'Создан',
    'Изменен',
    'Клики',
  ];
  
  export const dataFromDatabase = [
    {
      id: 1,
      name: 'Сайт 1',
      url: 'https://site1.com',
      clickPrice: 0.5,
      country: 'Россия',
      created: '01.01.2023',
      modified: '02.01.2023',
      clicks: 100,
    },
    {
      id: 2,
      name: 'Сайт 2',
      url: 'https://site2.com',
      clickPrice: 0.7,
      country: 'США',
      created: '01.01.2023',
      modified: '03.01.2023',
      clicks: 150,
    },
    {
      id: 3,
      name: 'Сайт 3',
      url: 'https://site3.com',
      clickPrice: 0.6,
      country: 'Канада',
      created: '01.01.2023',
      modified: '02.01.2023',
      clicks: 120,
    },
    {
      id: 4,
      name: 'Сайт 4',
      url: 'https://site4.com',
      clickPrice: 0.8,
      country: 'Австралия',
      created: '01.01.2023',
      modified: '04.01.2023',
      clicks: 180,
    },
    {
      id: 5,
      name: 'Сайт 5',
      url: 'https://site5.com',
      clickPrice: 0.4,
      country: 'Великобритания',
      created: '01.01.2023',
      modified: '03.01.2023',
      clicks: 90,
    },
    {
      id: 6,
      name: 'Сайт 6',
      url: 'https://site6.com',
      clickPrice: 0.6,
      country: 'Франция',
      created: '01.01.2023',
      modified: '05.01.2023',
      clicks: 200,
    },
  ];
  